export const ROUTES = {
    AUTH: '/auth',
    REGISTRATION: '/auth/registration',
    HOME: '/',
    JUICIEST: '/the-juiciest',
    CATEGORY: ':category',
    SUBCATEGORY: ':subcategory',
    RECIPE_ID: ':id',
    NEW_RECIPE: '/new-recipe',
    EDIT_RECIPE: '/edit-recipe',
    NOT_FOUND: '/not-found',
    VERIFICATION: '/verification',
    BLOGS: '/blogs',
    USER_ID: ':userId',
    PROFILE: '/profile',
    EDIT_DRAFT: '/edit-draft',
    DRAFT_ID: ':draftId',
    SETTINGS: '/settings',
};
